import { Router } from "express";
import { z } from "zod";
import { asyncRoute } from "../middleware/error";
import { validate, safeText } from "../middleware/validate";
import { requireAuth } from "../middleware/auth";
import { notFound, unavailable } from "../lib/errors";
import {
  describeSections,
  getSection,
  searchSections,
  statuteMeta,
  statuteReady,
} from "../lib/statute";

/**
 * Reference data: the criminal code, for the field an officer types a charge into.
 *
 * Behind requireAuth even though the Sanhita is a public document, because these
 * are not public endpoints — they exist to serve the FIR form, and an open search
 * endpoint is an open endpoint to rate-limit and monitor for no benefit. Anybody
 * who wants the Act can read it at indiacode.nic.in.
 *
 * Read-only, and there is no write path. The reference is a build artefact
 * regenerated by scripts/buildBnsReference.mjs when Parliament amends the Act, not
 * a table somebody edits.
 */

const router = Router();
router.use(requireAuth);

/** What the code is, and the caveat that travels with every severity it reports. */
router.get(
  "/statute",
  asyncRoute(async (_req, res) => {
    const meta = statuteMeta();
    if (!meta) {
      throw unavailable(
        "The statute reference is not available on this instance. Run " +
          "backend/scripts/buildBnsReference.mjs to generate it."
      );
    }
    res.json({ statute: meta });
  })
);

/**
 * Search the code.
 *
 * An empty query returns sections that state a punishment, because those are the
 * ones charged; the defining sections are reached by searching for them.
 */
router.get(
  "/sections",
  validate(
    z.object({
      q: safeText(80).optional(),
      limit: z.coerce.number().int().min(1).max(50).default(12),
    }),
    "query"
  ),
  asyncRoute(async (req, res) => {
    if (!statuteReady()) {
      return res.json({ sections: [], available: false });
    }
    const { q, limit } = req.query as unknown as { q?: string; limit: number };
    res.json({ sections: searchSections(q ?? "", limit), available: true });
  })
);

/** One section, by number. */
router.get(
  "/sections/:section",
  validate(z.object({ section: z.coerce.number().int().min(1).max(999) }), "params"),
  asyncRoute(async (req, res) => {
    const found = getSection(Number(req.params.section));
    if (!found) throw notFound("Section");
    res.json({ section: found });
  })
);

/**
 * What the code says about a set of citations, without registering anything.
 *
 * The FIR form calls this as the officer types, so the consequences of a charge —
 * which sections were recognised, what the gravest stated punishment is — are
 * visible before the case exists rather than after.
 */
router.post(
  "/sections/describe",
  validate(z.object({ sections: z.array(safeText(40)).max(20) })),
  asyncRoute(async (req, res) => {
    res.json({ statute: describeSections(req.body.sections) });
  })
);

export default router;
